name: firebase_auth_web
description: The web implementation of firebase_auth
homepage: https://github.com/firebase/flutterfire/tree/main/packages/firebase_auth/firebase_auth_web
repository: https://github.com/firebase/flutterfire/tree/main/packages/firebase_auth/firebase_auth_web
version: 5.14.3

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  firebase_auth_platform_interface:
    git:
      url: https://github.com/carlosbatistadev/flutterfire.git
      path: packages/firebase_auth/firebase_auth_platform_interface
  firebase_core:
    git:
      url: https://github.com/carlosbatistadev/flutterfire.git
      path: packages/firebase_core/firebase_core
  firebase_core_web:
    git:
      url: https://github.com/carlosbatistadev/flutterfire.git
      path: packages/firebase_core/firebase_core_web
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http_parser: ^4.0.0
  meta: ^1.8.0
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAuthWeb
        fileName: firebase_auth_web.dart
