name: firebase_storage_web
description: The web implementation of firebase_storage
homepage: https://github.com/firebase/flutterfire/tree/main/packages/firebase_storage/firebase_storage_web
repository: https://github.com/firebase/flutterfire/tree/main/packages/firebase_storage/firebase_storage_web
version: 3.10.13

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  _flutterfire_internals:
    git:
      url: https://github.com/carlosbatistadev/flutterfire.git
      path: packages/_flutterfire_internals

  async: ^2.5.0
  firebase_core:
    git:
      url: https://github.com/carlosbatistadev/flutterfire.git
      path: packages/firebase_core/firebase_core
  firebase_core_web:
    git:
      url: https://github.com/carlosbatistadev/flutterfire.git
      path: packages/firebase_core/firebase_core_web
  firebase_storage_platform_interface:
    git:
      url: https://github.com/carlosbatistadev/flutterfire.git
      path: packages/firebase_storage/firebase_storage_platform_interface
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: '>=0.13.0 <2.0.0'
  meta: ^1.8.0
  web: ^1.0.0

dev_dependencies:
  firebase_core_platform_interface:
    git:
      url: https://github.com/carlosbatistadev/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseStorageWeb
        fileName: firebase_storage_web.dart
