name: cloud_firestore_platform_interface
description: A common platform interface for the cloud_firestore plugin.
version: 6.6.8
homepage: https://github.com/firebase/flutterfire/tree/main/packages/cloud_firestore/cloud_firestore_platform_interface
repository: https://github.com/firebase/flutterfire/tree/main/packages/cloud_firestore/cloud_firestore_platform_interface

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  _flutterfire_internals:
    git:
      url: https://github.com/carlosbatistadev/flutterfire.git
      path: packages/_flutterfire_internals
  collection: ^1.15.0
  firebase_core:
    git:
      url: https://github.com/carlosbatistadev/flutterfire.git
      path: packages/firebase_core/firebase_core
  flutter:
    sdk: flutter
  meta: ^1.8.0
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  firebase_core_platform_interface:
    git:
      url: https://github.com/carlosbatistadev/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  pigeon: 11.0.1
  watcher: ^1.1.0

dependency_overrides:
  watcher: ^1.1.0
