name: cloud_firestore
description:
  Flutter plugin for Cloud Firestore, a cloud-hosted, noSQL database with
  live synchronization and offline support on Android and iOS.
homepage: https://firebase.google.com/docs/firestore
repository: https://github.com/firebase/flutterfire/tree/main/packages/cloud_firestore/cloud_firestore
version: 5.6.8
topics:
  - firebase
  - firestore
  - realtime
  - database

false_secrets:
  - example/**
  - dartpad/**

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  cloud_firestore_platform_interface:
    git:
      url: https://github.com/carlosbatistadev/flutterfire.git
      path: packages/cloud_firestore/cloud_firestore_platform_interface
  cloud_firestore_web:
    git:
      url: https://github.com/carlosbatistadev/flutterfire.git
      path: packages/cloud_firestore/cloud_firestore_web
  collection: ^1.0.0
  firebase_core:
    git:
      url: https://github.com/carlosbatistadev/flutterfire.git
      path: packages/firebase_core/firebase_core
  flutter:
    sdk: flutter
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.firestore
        pluginClass: FlutterFirebaseFirestorePlugin
      ios:
        pluginClass: FLTFirebaseFirestorePlugin
      macos:
        pluginClass: FLTFirebaseFirestorePlugin
      web:
        default_package: cloud_firestore_web
      windows:
        pluginClass: CloudFirestorePluginCApi

