name: firebase_messaging_web
description: The web implementation of firebase_messaging
homepage: https://github.com/firebase/flutterfire/tree/main/packages/firebase_messaging/firebase_messaging_web
repository: https://github.com/firebase/flutterfire/tree/main/packages/firebase_messaging/firebase_messaging_web
version: 3.10.6

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  _flutterfire_internals:
    git:
      url: https://github.com/carlosbatistadev/flutterfire.git
      path: packages/_flutterfire_internals
  firebase_core:
    git:
      url: https://github.com/carlosbatistadev/flutterfire.git
      path: packages/firebase_core/firebase_core
  firebase_core_web:
    git:
      url: https://github.com/carlosbatistadev/flutterfire.git
      path: packages/firebase_core/firebase_core_web
  firebase_messaging_platform_interface:
    git:
      url: https://github.com/carlosbatistadev/flutterfire.git
      path: packages/firebase_messaging/firebase_messaging_platform_interface
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.8.0
  web: ^1.0.0

dev_dependencies:
  firebase_core_platform_interface:
    git:
      url: https://github.com/carlosbatistadev/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseMessagingWeb
        fileName: firebase_messaging_web.dart
